"use client";

import type { Metadata } from "next";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "My Chakra App",
  description: "Generated by create next app and chakraUI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" ">
          <Providers>{children}</Providers>
      </body>
    </html>
  );
}
