"use client";

import type { Metadata } from "next";
import { Providers } from "./providers";
import { RecoilRoot } from "recoil";

export const metadata: Metadata = {
  title: "My Reddit App",
  description: "Generated by create next app and chakraUI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" ">
        <RecoilRoot>
          <Providers>{children}</Providers>
        </RecoilRoot>
      </body>
    </html>
  );
}
